version: '3.8'

services:
  postgres-command:
    image: postgres:latest
    container_name: command-user
    restart: always
    environment:
      POSTGRES_USER: furkan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: commanduser
    ports:
      - "5432:5432"
    volumes:
      - postgres_command_data:/var/lib/postgresql/data

  postgres-query:
    image: postgres:latest
    container_name: query-user
    restart: always
    environment:
      POSTGRES_USER: furkan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: queryuser
    ports:
      - "5433:5432"
    volumes:
      - postgres_query_data:/var/lib/postgresql/data

  postgres-package-command:
    image: postgres:latest
    container_name: package-command
    restart: always
    environment:
      POSTGRES_USER: furkan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: packagecommand
    ports:
      - "5434:5432"
    volumes:
      - postgres_package_command_data:/var/lib/postgresql/data

  extrapackage:
    image: postgres:latest
    container_name: extrapackage
    restart: always
    environment:
      POSTGRES_USER: furkan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: extrapackage
    ports:
      - "5435:5432"
    volumes:
      - postgres_extrapackage_data:/var/lib/postgresql/data

  extrafeatures:
    image: postgres:latest
    container_name: extrafeatures
    restart: always
    environment:
      POSTGRES_USER: furkan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: extrafeatures
    ports:
      - "5436:5432"
    volumes:
      - postgres_extrafeatures_data:/var/lib/postgresql/data

  shakewin:
    image: postgres:latest
    container_name: shakewin
    restart: always
    environment:
      POSTGRES_USER: furkan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: shakewin
    ports:
      - "5437:5432"
    volumes:
      - postgres_shakewin_data:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  mongodb:
    image: mongo:latest
    container_name: package-query-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: packagequerydb  # Veritabanı adı
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_command_data:
  postgres_query_data:
  postgres_package_command_data:
  postgres_extrapackage_data:
  postgres_extrafeatures_data:
  postgres_shakewin_data:
  mongodb_data:
