spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:http://localhost:8088"

  datasource:
    url: jdbc:postgresql://localhost:5438/payment
    username: furkan
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.kafka: DEBUG


iyzico:
  api:
    key: sandbox-gY2yNQTA9RI4IJWdrIPfBJgnk8MJzRoy
  secret:
    key: sandbox-dzqAVY4BVbLXY3omAEyQcRi1debCOr3w
  baseUrl: https://sandbox-api.iyzipay.com

  logging:
    level:
      org:
        springframework: DEBUG
      com:
        iyzipay: DEBUG